import asyncio
from typing import Sequence

from bluesky import RunEngine
from bluesky.callbacks import LiveTable
from databroker import catalog
from ophyd import Signal

from ...bl.set_command_rewriter import set_command_rewriter
from ...bluesky_measurement_execution_engine import BlueskyMeasurementExecutionEngine
from ...custom.epics.mexec.bluesky_measurement_engine import setup
from ...model.command import Command, BehaviourOnError, CommandSequence


def orm(*, horizontal_steerer_names: Sequence[str], vertical_steerer_names: Sequence[str],
        measurement_values: Sequence[float]):
    cmds_on_lattice = []
    for name in horizontal_steerer_names:
        for val in measurement_values:
            cmds_on_lattice.append(
                Command(id=name, property="delta_x_kick", value=val, behaviour_on_error=BehaviourOnError.stop))
    for name in vertical_steerer_names:
        for val in measurement_values:
            cmds_on_lattice.append(
                Command(id=name, property="delta_y_kick", value=val, behaviour_on_error=BehaviourOnError.stop))

    command_rewritter = set_command_rewriter()

    cmds_on_machine = CommandSequence(commands=[command_rewritter.forward(cmd) for cmd in cmds_on_lattice])

    # for a whole accelerator it would be a bit more complex
    # again review if here a software multiplexer would not be closer
    # to the task
    # todo: should be handled internally
    device_ids = set([cmd.id for cmd in cmds_on_machine.commands])

    # todo: should be handled internally
    devices = setup(device_ids=tuple(device_ids))
    bpms = devices["bpms"]
    steerers = devices["steerer_pcs"]
    async def _connect():
        return await steerers.connect()
    asyncio.run(_connect())

    print(f"{bpms.count.name=}")

    # todo: should be handled internally, needs to be overriden ?
    actuators = {name: pc for name, pc in steerers.settable_devices.items()}
    # used so that it is easier to see what is happening
    # could be included in the standard software multiplexer
    # todo: should these signals be generated by the measurment execution engine
    info_sigs = {name: Signal(name=name) for name in ["device_name", "channel_name", "channel_value"]}
    # todo: should be handled internally, but overridable
    lt = LiveTable([sig.name for _, sig in info_sigs.items()] + [bpms.count.name],  # + list(actuators.values())
                   default_prec=10, )
    # todo: need to address live plots
    RE = RunEngine()
    # here a databroker should be added so that data can be accessed
    # later on
    [RE.subscribe(consumer) for consumer in [lt]]
    db = catalog["heavy_local"]
    RE.subscribe(db.v1.insert)

    # mongodb can not store the command object ?
    # md = dict(commands_on_lattice=[asdict(cmd) for cmd in cmds_on_lattice.commands])
    md = {}
    mexec = BlueskyMeasurementExecutionEngine(run_engine=RE)
    uid = mexec.execute(commands_collection=cmds_on_machine.commands,  # need to add bpms
                        detectors=[bpms], actuators=actuators, info_signals=info_sigs, md=md, )
    print(f"Run created {uid=}")


if __name__ == "__main__":
    from ...bl.yellow_pages import yellow_pages
    yp = yellow_pages()
    orm(
        horizontal_steerer_names=[name[1:] for name in yp.horizontal_steerer_names()],
        vertical_steerer_names=[name[1:] for name in yp.vertical_steerer_names()],
        measurement_values=[0, 1e-5, 0, -1e-5, 0]
    )
