"""Demonstrator of using bluesky run engine as measurement executor

Todo:
   * Split up functionality.
   * Review how dynamically the required accelerator devices should
     be created.
   * Should a software multiplexer handle access to all the devices
     that are required for wrapping an accelerator

Here the steerers are created with devices of minimal functionallity.
Proper devices would use bluesky's synchronisation abilities.

"""
import json

# from ophyd import Signal
from bluesky.run_engine import RunEngine
from bluesky.callbacks import LiveTable
from databroker import catalog
from ophyd import Signal

from pamila_demo.bluesky_measurement_execution_engine import BlueskyMeasurementExecutionEngine
from pamila_demo.custom.epics.bluesky_measurement_engine import setup
from pamila_demo.model.command import CommandSequence, Command

def main():
    # lm, tm = build_managers()
    # command_rewritter=CommandRewriter(liasion_manager=lm, translation_service=tm)
    # load the commands that operate in lattice space and transform
    # them to machine state
    # cmds_on_lattice = CommandSequence(commands=[Command(**d) for d in tmp["commands"]])
    # cmds_on_machine = CommandSequence(
    #     commands=[
    #         command_rewritter.forward(cmd) for cmd in cmds_on_lattice.commands
    #     ]
    # )
    with open("orm_commands_dev_view.json") as fp:
        tmp = json.load(fp)
    cmds_on_machine = CommandSequence(commands=[Command(**d) for d in tmp["commands"]])    # dynamically create the steerer devices that are actually required
    # for a whole accelerator it would be a bit more complex
    # again review if here a software multiplexer would not be closer
    # to the task
    device_ids = set([cmd.id for cmd in cmds_on_machine.commands])

    bpms, steerers = setup(device_ids=tuple(device_ids))

    print(f"{bpms.count.name=}")

    actuators = {name: getattr(steerers.col, name) for name in steerers.col.component_names}
    # used so that it is easier to see what is happening
    # could be included in the standard software multiplexer
    # todo: should these signals be generated by the measurment execution engine
    info_sigs = {
        name: Signal(name=name) for name in ["device_name", "channel_name", "channel_value"]
    }
    lt = LiveTable(
        [sig.name for _, sig in info_sigs.items()] + [bpms.count.name],  # + list(actuators.values())
        default_prec=10,
    )
    #plots = orbit_plots.plots(
    #        magnet_name="device_name",
    #        ds=None,
    #        x_pos="/".join(["bpm_elem_data", "x"]),
    #        y_pos="/".join(["bpm_elem_data", "y"]),
    #         x_scale=1,
    #         y_scale=10/2**15,
    #         reading_count=bpms.count.name,
    #         bpms_to_exclude="BPMZ41T6R"
    #     )
    RE = RunEngine()
    # here a databroker should be added so that data can be accessed
    # later on
    [RE.subscribe(consumer) for consumer in [lt] ]
    db = catalog["heavy_local"]
    RE.subscribe(db.v1.insert)

    # mongodb can not store the command object ?
    # md = dict(commands_on_lattice=[asdict(cmd) for cmd in cmds_on_lattice.commands])
    md = {}
    mexec = BlueskyMeasurementExecutionEngine(run_engine=RE)
    uid = mexec.execute(
        commands_collection=cmds_on_machine.commands,
        # need to add bpms
        detectors=[bpms],
        actuators=actuators,
        info_signals=info_sigs,
        md=md,
    )
    print(f"Run created {uid=}")

if __name__ == "__main__":
    import matplotlib

    # should be selected by user / account settings
    # with qt liveplot works
    matplotlib.use('Qt5Agg')
    import matplotlib.pyplot as plt
    plt.ion()
    try:
        main()
    except Exception as e:
        raise e
    finally:
        plt.ioff()
        plt.show()